# Taken from https://github.com/danieldietrich/merge-objects/commit/c60f5f1e5bc978a5ebea0c80de24541cf6654a25
# Copyright (c) 2019 Daniel Dietrich https://danieldietrich.dev
# MIT License

on: pull_request

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/github-script@v4.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { repository: repo, pull_request: pr } = context.payload
            github.pulls.merge({
              owner: repo.owner.login,
              repo: repo.name,
              pull_number: pr.number
            })
