name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "1 1 * * 1"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@skip-native
        with:
          skip-native: true
      - run: kotlinc foo.kt -include-runtime -d hello.jar; java -jar hello.jar

      - run: kotlinc-native foo.kt
      - run: ./program.exe
        if: ${{ matrix.os == 'windows-latest' }}
      - run: ./program.kexe
        if: ${{ matrix.os != 'windows-latest' }}
      - run: kotlin foo.main.kts
