name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "1 1 * * 1"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: fwilhe2/setup-kotlin@0.0.4
    - run: kotlinc foo.kt -include-runtime -d hello.jar; java -jar hello.jar
    - run: kotlin foo.main.kts
    - uses: fwilhe2/setup-kotlin@main
      with:
        script: |
            #!/usr/bin/env kotlin
            println("::group::foobar")
            println("Hello from script")
            println("::endgroup::")
            println(System.getenv("GITHUB_ENV"))
            java.io.File(System.getenv("GITHUB_ENV")).appendText("action_state=yellow")
            java.io.File(System.getenv("GITHUB_ENV")).appendText("abc=xyz")
            java.io.File(System.getenv("GITHUB_ENV")).appendText("myvar=asasdfsdf")
    - run: echo $action_state; echo $abc; echo $myvar
      shell: bash
