name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "1 1 * * 1"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - run: 'echo "mv $1 ~/script.main.kts; kotlin ~/script.main.kts" > /opt/hostedtoolcache/kotlin/1.4.10/x64/kotlinc/bin/run.sh; chmod +x /opt/hostedtoolcache/kotlin/1.4.10/x64/kotlinc/bin/run.sh'
      - run: cat /opt/hostedtoolcache/kotlin/1.4.10/x64/kotlinc/bin
      - run: echo $PATH
      - run: |
            #!/usr/bin/env kotlin
            @file:Import("common.main.kts")

            withGroup("debug"){
              println(System.getenv("GITHUB_ENV"))
            }

            println("abc")

            println("Using Kotlin " + getInput("version"))

            exportVariable("action_state", "yellow")
            exportVariable("abc", "xyz")
            exportVariable("myvar", "asasdfsdf")
        shell: run.sh {0}          
