name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "1 1 * * 1"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - run: |
            #!/usr/bin/env kotlin
            @file:Import("common.main.kts")

            withGroup("debug"){
              println(System.getenv("GITHUB_ENV"))
            }

            exportVariable("action_state", "yellow")
        shell: kotlin {0}
